version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/ubuntu/blog-app
    ports:
      - "8000:8000"

    labels:
      kompose.service.type: LoadBalancer